//! Certified Mordell–Weil ranks over `ℚ` by **descent via 2-isogeny**.
//!
//! This module handles elliptic curves over `ℚ` with a rational 2-torsion point.
//! Moving that point to the origin puts the curve in the form
//!
//! ```text
//! E  : y² = x³ + a·x² + b·x,          a, b ∈ ℤ,  b ≠ 0,  a² − 4b ≠ 0,
//! ```
//!
//! which is the domain of the 2-isogeny `φ : E → E'` onto
//!
//! ```text
//! E' : Y² = X³ − 2a·X² + (a² − 4b)·X
//! ```
//!
//! (with dual `φ̂ : E' → E`, `φ̂ ∘ φ = [2]`). [`TwoIsogenyCurve`] stores `(a, b)`;
//! [`TwoIsogenyCurve::from_short_weierstrass`] converts a short-Weierstrass
//! [`EllipticCurve<Rational>`] with a rational 2-torsion point into this shape.
//!
//! # The descent
//!
//! For a curve `C : y² = x³ + a·x² + b·x` let
//!
//! ```text
//! α_C : C(ℚ) → ℚ*/ℚ*²,   (x, y) ↦ x,   (0, 0) ↦ b,   O ↦ 1.
//! ```
//!
//! This is a homomorphism whose kernel is the image of the dual isogeny, and
//! `d ∈ ℚ*/ℚ*²` lies in its image iff `d` is (the class of) a squarefree divisor of
//! `b` for which the quartic
//!
//! ```text
//! N_d :  w² = d·u⁴ + a·u²v² + (b/d)·v⁴
//! ```
//!
//! has a rational solution with `(u, v) ≠ (0, 0)`; the point is
//! `(d·u²/v², d·u·w/v³)` (Silverman–Tate, *Rational Points on Elliptic Curves*,
//! §III.5; Silverman, *The Arithmetic of Elliptic Curves* (AEC), Prop. X.4.9).
//! The **Selmer group** attached to `α_C` is the set of those `d` for which `N_d`
//! is solvable over `ℝ` and over every `ℚ_p`; it is a finite `𝔽₂`-vector space
//! containing `α_C(C(ℚ))`, and only the primes `p | 2·b·(a² − 4b)` need testing.
//!
//! In AEC's notation the Selmer group computed from `E` (generated by `−1` and
//! the primes of `b`) is `S^(φ̂)(E'/ℚ)`, which contains `E(ℚ)/φ̂(E'(ℚ))`, and the
//! one computed from `E'` (primes of `a² − 4b`) is `S^(φ)(E/ℚ)`, containing
//! `E'(ℚ)/φ(E(ℚ))`. With `r = rank E(ℚ)`, the classical formula
//! (Silverman–Tate §III.6, AEC Prop. X.6.2(c) and its proof)
//!
//! ```text
//! 2^r = #α_E(E(ℚ)) · #α_E'(E'(ℚ)) / 4
//! ```
//!
//! gives `r = dim α_E + dim α_E' − 2` and hence the upper bound
//!
//! ```text
//! r ≤ U := dim S^(φ)(E/ℚ) + dim S^(φ̂)(E'/ℚ) − 2,
//! ```
//!
//! with equality iff `Ш(E/ℚ)[φ] = Ш(E'/ℚ)[φ̂] = 0`. A lower bound comes from
//! global solutions of the quartics found by a bounded search: every solution
//! found exhibits an element of the image of `α_E` (resp. `α_E'`), so if the
//! found classes span spaces of dimensions `f`, `f'`, then `r ≥ f + f' − 2`.
//!
//! # Local solubility
//!
//! Over `ℝ`, `N_d` is solvable iff `d > 0`, or `b/d > 0`, or `a > 0` and
//! `a² − 4b > 0` (a positive root of `d·X² + a·X + b/d`).
//!
//! Over `ℚ_p` every point of `ℙ¹(ℚ_p)` is `(x : 1)` with `x ∈ ℤ_p` or `(1 : p·z)`
//! with `z ∈ ℤ_p`, so solubility reduces to deciding whether a polynomial
//! `g ∈ ℤ[x]` of degree ≤ 4 with distinct roots takes a square value in `ℚ_p` on
//! `ℤ_p`. This is decided **exactly** by a recursion over residue discs
//! `x₀ + pⁿℤ_p` in the style of the local solubility tests of Merriman–Siksek–
//! Smart and Cremona (*Algorithms for Modular Elliptic Curves*, §3.5–3.6):
//!
//! - **Hensel**: if `v(g(x₀)) > 2·v(g'(x₀))` and `v(g(x₀)) − v(g'(x₀)) ≥ n`, a root
//!   of `g` lies in the disc, and a zero is a square;
//! - **odd `p`**: writing `g(x₀ + pⁿt) = p^μ·(h̄(t) + p·…)` with `h̄ ≢ 0 mod p`, a
//!   residue `t` with `h̄(t) ≠ 0` decides its sub-disc (square iff `μ` even and
//!   `h̄(t)` a quadratic residue); only roots of `h̄` mod `p` need refinement. For
//!   large `p`, the existence of a good residue is read off from whether `h̄` is a
//!   constant times a square (Weil's bound `|Σ χ(h̄(t))| ≤ 3√p` handles the rest)
//!   and roots mod `p` come from Cantor–Zassenhaus, so the cost is polynomial in
//!   `log p`;
//! - **`p = 2`**: when every Taylor term of order ≥ 1 on the disc has valuation
//!   at least `v(g(x₀)) + 3`, the class of `g` mod squares is constant on the disc
//!   (a 2-adic unit is a square iff it is `≡ 1 mod 8`); otherwise the disc is
//!   halved.
//!
//! Since `g` has distinct roots the recursion terminates: away from the roots the
//! valuation of `g` is bounded and the Taylor terms eventually dominate, and near
//! a simple root the Hensel test fires. All arithmetic is exact integer
//! arithmetic; there is no precision guess. A generous depth cap exists only as a
//! guard: if it were ever hit, the class is conservatively kept in the Selmer
//! group (so the upper bound stays valid) and the descent is flagged inexact,
//! which disables the [2-converse](RankMethod::TwoConverse) path.
//!
//! # Certificates
//!
//! [`TwoIsogenyCurve::certified_rank`] returns a [`RankCertificate`]:
//!
//! - [`RankMethod::SelmerBound`] — `U = 0`, so `r = 0` (classical);
//! - [`RankMethod::PointsMeetSelmerBound`] — the independent points found give
//!   `r ≥ U` (classical);
//! - [`RankMethod::TwoConverse`] — `U = 1` and no point of infinite order was
//!   found; `r = 1` follows from a **2026 unrefereed preprint** (see below);
//! - otherwise [`RankCertificate::Bounds`].
//!
//! ## The 2-converse path
//!
//! Put `d₂(E) = dim Sel₂(E/ℚ) − dim E(ℚ)[2]`. OpenAI, *Goldfeld's analytic
//! density conjecture and the 2-converse for elliptic curves* (preprint,
//! September 23, 2026), Corollary "A finite Selmer criterion" (with Lemma
//! "Finite descent and corank"), proves: **if `d₂(E) ∈ {0, 1}` then
//! `ord_{s=1} L(E, s) = rank E(ℚ) = d₂(E)`, `Ш(E/ℚ)` is finite and
//! `Ш(E/ℚ)[2^∞] = 0`.** (The rational-two-torsion case is also treated
//! separately in OpenAI, *A pointwise 2-converse for elliptic curves with
//! rational two-torsion*, preprint, September 24, 2026, Theorem 1.1, stated for
//! the full 2^∞-Selmer corank.) These results are recent and **not refereed**;
//! a certificate with [`RankMethod::TwoConverse`] is only as reliable as that
//! preprint, which is why the method is reported separately.
//!
//! The 2-isogeny Selmer groups do not determine `Sel₂(E)` exactly, so the
//! criterion is applied through the following classical inequalities. From the
//! Kummer sequence, `d₂(E) = r + dim Ш(E)[2]`; from
//! `0 → Ш(E)[φ] → Ш(E)[2] →φ Ш(E')[φ̂]`, `dim Ш(E)[2] ≤ dim Ш(E)[φ] + dim Ш(E')[φ̂]`;
//! hence `d₂(E) ≤ r + dim Ш(E)[φ] + dim Ш(E')[φ̂] = U`, and symmetrically
//! `d₂(E') ≤ U`. When the Selmer groups are computed exactly and `U = 1`, both
//! `d₂(E)` and `d₂(E')` lie in `{0, 1}`; the corollary applied to `E` and to `E'`
//! gives `Ш(E)[2^∞] = Ш(E')[2^∞] = 0`, so `r = U − dim Ш(E)[φ] − dim Ш(E')[φ̂] = 1`
//! (and then `d₂(E) = 1` and the analytic rank is 1). Only `U = 1` uses the
//! preprint; `U = 0 ⇒ r = 0` is classical.
//!
//! # Clean-room provenance
//!
//! Silverman, *The Arithmetic of Elliptic Curves* §X.4 and §X.6; Silverman–Tate,
//! *Rational Points on Elliptic Curves* §III.5–III.6; Cremona, *Algorithms for
//! Modular Elliptic Curves* §3.5–3.6; Cohen, *A Course in Computational Algebraic
//! Number Theory* §3.4 (Cantor–Zassenhaus); the preprints cited above. No
//! third-party source code was consulted.

use alloc::vec::Vec;

use crate::elliptic::EllipticCurve;
use crate::int::Int;
use crate::rational::Rational;

/// Default half-width of the search box used for global points on the quartics.
pub const DEFAULT_SEARCH_BOUND: u32 = 400;

/// An elliptic curve `y² = x³ + a·x² + b·x` over `ℚ` with integer `a`, `b`
/// (`b ≠ 0`, `a² − 4b ≠ 0`), i.e. a curve with the rational 2-torsion point
/// `(0, 0)`. See the [module documentation](self).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TwoIsogenyCurve {
    a: Int,
    b: Int,
}

/// The change of variables produced by
/// [`TwoIsogenyCurve::from_short_weierstrass`]: a point `(x, y)` of the short
/// Weierstrass curve maps to `(X, Y) = (λ²·(x − x₀), λ³·y)` on the
/// [`TwoIsogenyCurve`].
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct WeierstrassToTwoIsogeny {
    /// The rational root `x₀` of `x³ + A·x + B` that is moved to the origin.
    pub x_shift: Rational,
    /// The positive integer scale `λ`.
    pub scale: Int,
}

impl WeierstrassToTwoIsogeny {
    /// Maps an affine point `(x, y)` of the short Weierstrass model to the
    /// [`TwoIsogenyCurve`] model.
    pub fn map_point(&self, x: &Rational, y: &Rational) -> (Rational, Rational) {
        let l2 = Rational::from_integer(self.scale.square());
        let l3 = Rational::from_integer(self.scale.pow(3));
        (x.sub(&self.x_shift).mul(&l2), y.mul(&l3))
    }
}

/// How a [`RankCertificate::Proven`] rank was established.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RankMethod {
    /// The 2-isogeny Selmer bound is `0`, so the rank is `0` (classical:
    /// Silverman–Tate §III.6, AEC §X.6).
    SelmerBound,
    /// Points found by search span a subgroup whose rank equals the Selmer upper
    /// bound (classical).
    PointsMeetSelmerBound,
    /// The Selmer bound is `1` and the rank equals `1` by the 2-converse /
    /// finite Selmer criterion of the **unrefereed 2026 preprint** cited in the
    /// [module documentation](self#the-2-converse-path). Callers that only accept
    /// classical results should treat this as `Bounds { lower: 0, upper: 1 }`.
    TwoConverse,
}

/// The outcome of [`TwoIsogenyCurve::certified_rank`].
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RankCertificate {
    /// The rank is exactly `rank`, established by `method`.
    Proven {
        /// The Mordell–Weil rank of `E(ℚ)`.
        rank: u32,
        /// The argument that proves it.
        method: RankMethod,
    },
    /// Rigorous bounds `lower ≤ rank E(ℚ) ≤ upper` that do not meet.
    Bounds {
        /// Lower bound from independent points found by search.
        lower: u32,
        /// Upper bound `dim S^(φ) + dim S^(φ̂) − 2`.
        upper: u32,
    },
}

impl RankCertificate {
    /// The proven rank, if any (including [`RankMethod::TwoConverse`]).
    pub fn rank(&self) -> Option<u32> {
        match self {
            RankCertificate::Proven { rank, .. } => Some(*rank),
            RankCertificate::Bounds { .. } => None,
        }
    }
}

/// One side of a 2-isogeny descent: the Selmer group attached to
/// `α_C : C(ℚ) → ℚ*/ℚ*²` and the part of the image `α_C(C(ℚ))` exhibited by
/// global points.
#[derive(Clone, Debug)]
pub struct SelmerData {
    /// All elements of the Selmer group, as squarefree integers (`1` included).
    pub selmer: Vec<Int>,
    /// `dim_𝔽₂` of the Selmer group.
    pub selmer_dim: u32,
    /// A basis of the subspace spanned by the classes `d` for which a global
    /// point of `N_d` was found (as squarefree integers).
    pub image_basis: Vec<Int>,
    /// Whether every local test was decided (always `true` in practice).
    pub exact: bool,
}

/// The full data of a 2-isogeny descent on `E` and `E'`.
#[derive(Clone, Debug)]
pub struct TwoIsogenyDescent {
    /// Data from `E : y² = x³ + a·x² + b·x` (generated by `−1` and the primes of
    /// `b`): this Selmer group is `S^(φ̂)(E'/ℚ)` and the image is
    /// `α_E(E(ℚ)) ≅ E(ℚ)/φ̂(E'(ℚ))`.
    pub curve: SelmerData,
    /// Data from `E' : y² = x³ − 2a·x² + (a² − 4b)·x`: Selmer group
    /// `S^(φ)(E/ℚ)` and image `α_E'(E'(ℚ)) ≅ E'(ℚ)/φ(E(ℚ))`.
    pub isogenous: SelmerData,
    /// `rank E(ℚ) ≥ lower` from the found points.
    pub lower: u32,
    /// `rank E(ℚ) ≤ upper = dim S^(φ) + dim S^(φ̂) − 2`.
    pub upper: u32,
}

impl TwoIsogenyCurve {
    /// The curve `y² = x³ + a·x² + b·x`, or `None` if it is singular
    /// (`b = 0` or `a² − 4b = 0`).
    pub fn new(a: Int, b: Int) -> Option<TwoIsogenyCurve> {
        if b.is_zero() || a.square() == b.mul_2k(2) {
            return None;
        }
        Some(TwoIsogenyCurve { a, b })
    }

    /// The coefficient `a`.
    pub fn a(&self) -> &Int {
        &self.a
    }

    /// The coefficient `b`.
    pub fn b(&self) -> &Int {
        &self.b
    }

    /// The 2-isogenous curve `E' : y² = x³ − 2a·x² + (a² − 4b)·x`.
    pub fn isogenous(&self) -> TwoIsogenyCurve {
        TwoIsogenyCurve {
            a: self.a.mul_2k(1).neg(),
            b: self.a.square().sub(&self.b.mul_2k(2)),
        }
    }

    /// The short Weierstrass model `y² = x³ + A·x + B` obtained by `x ↦ x − a/3`.
    pub fn to_short_weierstrass(&self) -> EllipticCurve<Rational> {
        // x³ + a x² + b x with x = t − a/3: A = b − a²/3, B = 2a³/27 − ab/3.
        let a = Rational::from_integer(self.a.clone());
        let b = Rational::from_integer(self.b.clone());
        let three = Rational::from_integer(Int::from(3));
        let a2 = a.mul(&a);
        let big_a = b.sub(&a2.div(&three));
        let big_b = a2
            .mul(&a)
            .mul(&Rational::new(Int::from(2), Int::from(27)))
            .sub(&a.mul(&b).div(&three));
        EllipticCurve::new(big_a, big_b).expect("non-singular by construction")
    }

    /// Moves a short Weierstrass curve `y² = x³ + A·x + B` over `ℚ` with a
    /// rational 2-torsion point into the form `y² = x³ + a·x² + b·x` with integer
    /// `a`, `b`. Returns `None` if `x³ + A·x + B` has no rational root.
    ///
    /// If there are three rational roots, the smallest is used.
    pub fn from_short_weierstrass(
        curve: &EllipticCurve<Rational>,
    ) -> Option<(TwoIsogenyCurve, WeierstrassToTwoIsogeny)> {
        let (ca, cb) = (curve.a(), curve.b());
        let den = ca.denominator().lcm(cb.denominator());
        // x = X/den: X³ + (A·den²)·X + B·den³, a monic integer cubic.
        let p = ca.mul(&Rational::from_integer(den.square())).to_integer()?;
        let q = cb.mul(&Rational::from_integer(den.pow(3))).to_integer()?;
        let root = integer_roots_depressed_cubic(&p, &q).into_iter().next()?;
        let x0 = Rational::new(root, den);
        // Translate: (x + x0)³ + A(x + x0) + B = x³ + 3x0·x² + (3x0² + A)·x.
        let three = Rational::from_integer(Int::from(3));
        let ar = three.mul(&x0);
        let br = three.mul(&x0).mul(&x0).add(ca);
        let lambda = ar.denominator().lcm(br.denominator());
        let a = ar
            .mul(&Rational::from_integer(lambda.square()))
            .to_integer()?;
        let b = br
            .mul(&Rational::from_integer(lambda.pow(4)))
            .to_integer()?;
        let c = TwoIsogenyCurve::new(a, b)?;
        Some((
            c,
            WeierstrassToTwoIsogeny {
                x_shift: x0,
                scale: lambda,
            },
        ))
    }

    /// Runs the 2-isogeny descent on `E` and `E'`, searching for global points
    /// on the quartics `N_d` with `|u|, |v| ≤ search_bound`.
    pub fn two_isogeny_descent(&self, search_bound: u32) -> TwoIsogenyDescent {
        let iso = self.isogenous();
        let curve = selmer_data(&self.a, &self.b, search_bound);
        let isogenous = selmer_data(&iso.a, &iso.b, search_bound);
        let upper = (curve.selmer_dim + isogenous.selmer_dim).saturating_sub(2);
        let found = curve.image_basis.len() as u32 + isogenous.image_basis.len() as u32;
        let lower = found.saturating_sub(2);
        TwoIsogenyDescent {
            curve,
            isogenous,
            lower,
            upper,
        }
    }

    /// The certified rank with the default point-search bound
    /// [`DEFAULT_SEARCH_BOUND`]. See [`RankCertificate`] and the
    /// [module documentation](self#certificates).
    pub fn certified_rank(&self) -> RankCertificate {
        self.certified_rank_with_search_bound(DEFAULT_SEARCH_BOUND)
    }

    /// The certified rank, searching for points with `|u|, |v| ≤ search_bound`.
    /// The returned certificate is never wrong; only
    /// [`RankMethod::TwoConverse`] depends on the unrefereed 2026 preprint.
    pub fn certified_rank_with_search_bound(&self, search_bound: u32) -> RankCertificate {
        certificate_from_descent(&self.two_isogeny_descent(search_bound))
    }
}

/// Turns descent data into a [`RankCertificate`].
pub fn certificate_from_descent(desc: &TwoIsogenyDescent) -> RankCertificate {
    let (lower, upper) = (desc.lower, desc.upper);
    debug_assert!(lower <= upper, "2-descent: lower bound exceeds upper bound");
    if lower > upper {
        // Inconsistent data (an internal bug): never certify anything from it.
        return RankCertificate::Bounds { lower, upper };
    }
    if upper == 0 {
        return RankCertificate::Proven {
            rank: 0,
            method: RankMethod::SelmerBound,
        };
    }
    if lower == upper {
        return RankCertificate::Proven {
            rank: upper,
            method: RankMethod::PointsMeetSelmerBound,
        };
    }
    // U = 1 with exact Selmer groups: d₂(E), d₂(E') ≤ 1, so the finite Selmer
    // criterion kills Ш(E)[2^∞] and Ш(E')[2^∞], forcing rank = U = 1.
    if upper == 1 && desc.curve.exact && desc.isogenous.exact {
        return RankCertificate::Proven {
            rank: 1,
            method: RankMethod::TwoConverse,
        };
    }
    RankCertificate::Bounds { lower, upper }
}

impl EllipticCurve<Rational> {
    /// Certified rank of a curve over `ℚ` with a rational 2-torsion point, via
    /// [`TwoIsogenyCurve::from_short_weierstrass`] and
    /// [`TwoIsogenyCurve::certified_rank`]. `None` if the cubic has no rational
    /// root (no rational 2-torsion).
    pub fn certified_rank(&self) -> Option<RankCertificate> {
        TwoIsogenyCurve::from_short_weierstrass(self).map(|(c, _)| c.certified_rank())
    }
}

/// Whether `w² = d·u⁴ + a·u²v² + e·v⁴` has a real solution with `(u, v) ≠ 0`.
/// Requires `d·e ≠ 0`.
pub fn quartic_is_real_soluble(d: &Int, a: &Int, e: &Int) -> bool {
    d.is_positive() || e.is_positive() || (a.is_positive() && a.square() > d.mul(e).mul_2k(2))
}

/// Whether `w² = d·u⁴ + a·u²v² + e·v⁴` has a solution over `ℚ_p` with
/// `(u, v) ≠ (0, 0)`, for a prime `p`. Requires `d·e·(a² − 4de) ≠ 0`.
///
/// Returns `None` only if the internal recursion guard is hit (never observed;
/// the recursion provably terminates).
pub fn quartic_is_locally_soluble(d: &Int, a: &Int, e: &Int, p: &Int) -> Option<bool> {
    assert!(
        !d.is_zero() && !e.is_zero() && a.square() != d.mul(e).mul_2k(2),
        "quartic must have distinct roots"
    );
    let cap = 64 + 4 * [d, a, e].iter().map(|c| c.bit_len()).max().unwrap_or(0) + 8 * p.bit_len();
    let zero = Int::ZERO;
    // Chart (x : 1): g(x) = d x⁴ + a x² + e.
    let g1 = [e.clone(), zero.clone(), a.clone(), zero.clone(), d.clone()];
    // Chart (1 : p z): g(z) = d + a p² z² + e p⁴ z⁴.
    let p2 = p.square();
    let g2 = [
        d.clone(),
        zero.clone(),
        a.mul(&p2),
        zero,
        e.mul(&p2.square()),
    ];
    let mut unknown = false;
    for g in [&g1, &g2] {
        match zp_square_value(g, p, &Int::ZERO, 0, cap) {
            Some(true) => return Some(true),
            Some(false) => {}
            None => unknown = true,
        }
    }
    if unknown { None } else { Some(false) }
}

// ---------------------------------------------------------------------------
// Selmer group computation.
// ---------------------------------------------------------------------------

/// Distinct primes of `|n|`, sorted.
fn distinct_primes(n: &Int) -> Vec<Int> {
    n.factor_exponents().into_iter().map(|(p, _)| p).collect()
}

/// The squarefree integer with sign bit 0 and prime bits 1.. of `mask`.
fn mask_to_int(mask: u64, primes: &[Int]) -> Int {
    let mut d = if mask & 1 == 1 {
        Int::MINUS_ONE
    } else {
        Int::ONE
    };
    for (i, p) in primes.iter().enumerate() {
        if mask >> (i + 1) & 1 == 1 {
            d = d.mul(p);
        }
    }
    d
}

/// Inserts `v` into an `𝔽₂` xor-basis; returns `true` if it was independent.
fn xor_basis_insert(basis: &mut Vec<u64>, mut v: u64) -> bool {
    for &b in basis.iter() {
        v = v.min(v ^ b);
    }
    if v == 0 {
        return false;
    }
    basis.push(v);
    basis.sort_unstable_by(|x, y| y.cmp(x));
    true
}

fn in_span(basis: &[u64], mut v: u64) -> bool {
    for &b in basis {
        v = v.min(v ^ b);
    }
    v == 0
}

/// Selmer group of `α_C` for `C : y² = x³ + a x² + b x`, plus global images.
fn selmer_data(a: &Int, b: &Int, search_bound: u32) -> SelmerData {
    let primes = distinct_primes(b);
    assert!(
        primes.len() < 63,
        "2-isogeny descent: too many prime factors"
    );
    let disc = a.square().sub(&b.mul_2k(2));
    let mut bad = primes.clone();
    bad.extend(distinct_primes(&disc));
    bad.push(Int::from(2));
    bad.sort();
    bad.dedup();

    let count = 1u64 << (primes.len() + 1);
    let mut members: Vec<u64> = Vec::new();
    let mut exact = true;
    for mask in 0..count {
        let d = mask_to_int(mask, &primes);
        let e = b.div_exact(&d);
        if !quartic_is_real_soluble(&d, a, &e) {
            continue;
        }
        let mut ok = true;
        let mut undecided = false;
        for p in &bad {
            match quartic_is_locally_soluble(&d, a, &e, p) {
                Some(true) => {}
                Some(false) => {
                    ok = false;
                    break;
                }
                None => undecided = true,
            }
        }
        if ok {
            if undecided {
                exact = false;
            }
            members.push(mask);
        }
    }
    // Span (equals the member set when exact; a valid over-approximation
    // otherwise).
    let mut sel_basis: Vec<u64> = Vec::new();
    for &m in &members {
        xor_basis_insert(&mut sel_basis, m);
    }
    let selmer_dim = sel_basis.len() as u32;
    debug_assert!(!exact || members.len() as u64 == 1u64 << selmer_dim);

    // Global points: 1 and b are always images (O and (0, 0)).
    let mut img: Vec<u64> = Vec::new();
    let b_mask = int_to_mask(b, &primes);
    xor_basis_insert(&mut img, b_mask);
    for &m in &members {
        if in_span(&img, m) {
            continue;
        }
        let d = mask_to_int(m, &primes);
        let e = b.div_exact(&d);
        if quartic_has_global_point(&d, a, &e, search_bound) {
            xor_basis_insert(&mut img, m);
        }
    }
    debug_assert!(img.iter().all(|&m| in_span(&sel_basis, m)));
    SelmerData {
        selmer: members.iter().map(|&m| mask_to_int(m, &primes)).collect(),
        selmer_dim,
        image_basis: img.iter().map(|&m| mask_to_int(m, &primes)).collect(),
        exact,
    }
}

/// The mask of the squarefree part of `n` (whose primes all lie in `primes`).
fn int_to_mask(n: &Int, primes: &[Int]) -> u64 {
    let mut mask = u64::from(n.is_negative());
    for (i, p) in primes.iter().enumerate() {
        let mut k = 0u32;
        let mut m = n.abs();
        while let Some((q, r)) = m.div_rem(p) {
            if !r.is_zero() {
                break;
            }
            m = q;
            k += 1;
        }
        if !k.is_multiple_of(2) {
            mask |= 1 << (i + 1);
        }
    }
    mask
}

/// Searches `w² = d u⁴ + a u² v² + e v⁴` for `0 ≤ u ≤ B`, `1 ≤ v ≤ B` coprime
/// (and `(u, v) = (1, 0)`).
fn quartic_has_global_point(d: &Int, a: &Int, e: &Int, bound: u32) -> bool {
    if d.sqrt_exact().is_some() {
        return true; // (u, v) = (1, 0)
    }
    if bound == 0 {
        return false;
    }
    let bound_u = u128::from(bound);
    let small: Option<Vec<i128>> = [d, a, e].iter().map(|c| c.to_i128()).collect();
    if let Some(c) = small {
        let cmax = c.iter().map(|x| x.unsigned_abs()).max().unwrap_or(0);
        let b4 = bound_u.pow(4);
        if cmax.checked_mul(3 * b4).is_some_and(|m| m < (1u128 << 126)) {
            let (d, a, e) = (c[0], c[1], c[2]);
            for v in 1..=i128::from(bound) {
                let v2 = v * v;
                let ev4 = e * v2 * v2;
                for u in 0..=i128::from(bound) {
                    if gcd_u(u as u128, v as u128) != 1 {
                        continue;
                    }
                    let u2 = u * u;
                    let val = d * u2 * u2 + a * u2 * v2 + ev4;
                    if val >= 0 && is_square_u128(val as u128) {
                        return true;
                    }
                }
            }
            return false;
        }
    }
    for v in 1..=bound {
        let vi = Int::from(v);
        let v2 = vi.square();
        let ev4 = e.mul(&v2.square());
        for u in 0..=bound {
            if gcd_u(u128::from(u), u128::from(v)) != 1 {
                continue;
            }
            let u2 = Int::from(u).square();
            let val = d.mul(&u2.square()).add(&a.mul(&u2).mul(&v2)).add(&ev4);
            if val.sqrt_exact().is_some() {
                return true;
            }
        }
    }
    false
}

fn gcd_u(mut a: u128, mut b: u128) -> u128 {
    while b != 0 {
        let t = a % b;
        a = b;
        b = t;
    }
    a
}

fn is_square_u128(n: u128) -> bool {
    // Quick residue filter mod 64.
    if (0x0202_0212_0203_0213u64 >> (n & 63)) & 1 == 0 {
        return false;
    }
    let r = n.isqrt();
    r * r == n
}

// ---------------------------------------------------------------------------
// p-adic solubility of w² = g(x), x ∈ ℤ_p.
// ---------------------------------------------------------------------------

/// `v_p(n)` for `n ≠ 0`.
fn val(n: &Int, p: &Int) -> u32 {
    if p == &Int::from(2) {
        return n.trailing_zeros();
    }
    let mut k = 0;
    let mut m = n.clone();
    loop {
        let (q, r) = m.div_rem(p).expect("p ≠ 0");
        if !r.is_zero() {
            return k;
        }
        m = q;
        k += 1;
    }
}

/// Taylor coefficients `g_i(x₀) = Σ_j C(j, i)·g_j·x₀^{j−i}` of a degree-≤4 `g`.
fn taylor(g: &[Int; 5], x0: &Int) -> [Int; 5] {
    const BINOM: [[i64; 5]; 5] = [
        [1, 0, 0, 0, 0],
        [1, 1, 0, 0, 0],
        [1, 2, 1, 0, 0],
        [1, 3, 3, 1, 0],
        [1, 4, 6, 4, 1],
    ];
    let mut pw = [Int::ONE, Int::ZERO, Int::ZERO, Int::ZERO, Int::ZERO];
    for k in 1..5 {
        pw[k] = pw[k - 1].mul(x0);
    }
    core::array::from_fn(|i| {
        let mut acc = Int::ZERO;
        for j in i..5 {
            if !g[j].is_zero() {
                acc = acc.add(&g[j].mul(&pw[j - i]).mul(&Int::from(BINOM[j][i])));
            }
        }
        acc
    })
}

/// Whether some `x ∈ x₀ + pⁿℤ_p` makes `g(x)` a square in `ℚ_p`.
fn zp_square_value(g: &[Int; 5], p: &Int, x0: &Int, n: u32, cap: u32) -> Option<bool> {
    if n > cap {
        return None;
    }
    let t = taylor(g, x0);
    if t[0].is_zero() {
        return Some(true);
    }
    let v = val(&t[0], p);
    // Hensel: a genuine root of g in the disc.
    if !t[1].is_zero() {
        let c = val(&t[1], p);
        if v > 2 * c && v - c >= n {
            return Some(true);
        }
    }
    let pn = p.pow(n);
    if p == &Int::from(2) {
        let m = (1..5)
            .filter(|&i| !t[i].is_zero())
            .map(|i| val(&t[i], p) + i as u32 * n)
            .min();
        if m.is_none_or(|m| m >= v + 3) {
            let unit = t[0].div_2k_trunc(v);
            return Some(v.is_multiple_of(2) && unit.rem_euclid(&Int::from(8)).is_one());
        }
        let mut unknown = false;
        for s in 0..2 {
            let child = x0.add(&pn.mul(&Int::from(s)));
            match zp_square_value(g, p, &child, n + 1, cap) {
                Some(true) => return Some(true),
                Some(false) => {}
                None => unknown = true,
            }
        }
        return if unknown { None } else { Some(false) };
    }
    // Odd p: g(x₀ + pⁿ s) = Σ t_i p^{n i} s^i = p^μ (h̄(s) + p·…).
    let vals: Vec<Option<u32>> = (0..5)
        .map(|i| (!t[i].is_zero()).then(|| val(&t[i], p) + i as u32 * n))
        .collect();
    let mu = vals.iter().flatten().copied().min().expect("t[0] ≠ 0");
    let hbar: Vec<Int> = (0..5)
        .map(|i| match vals[i] {
            Some(vi) if vi == mu => {
                let unit = t[i].div_exact(&p.pow(vi - i as u32 * n));
                unit.rem_euclid(p)
            }
            _ => Int::ZERO,
        })
        .collect();
    let hbar = trim(hbar);
    if mu.is_multiple_of(2) && has_nonzero_residue_value(&hbar, p) {
        return Some(true);
    }
    let mut unknown = false;
    for r in roots_mod_p(&hbar, p) {
        let child = x0.add(&pn.mul(&r));
        match zp_square_value(g, p, &child, n + 1, cap) {
            Some(true) => return Some(true),
            Some(false) => {}
            None => unknown = true,
        }
    }
    if unknown { None } else { Some(false) }
}

/// Below this, residue questions mod `p` are answered by exhaustive scan.
const SMALL_P: i64 = 1024;

/// Whether `h(s)` is a nonzero quadratic residue for some `s ∈ 𝔽_p` (`p` odd).
fn has_nonzero_residue_value(h: &[Int], p: &Int) -> bool {
    if let Some(ps) = p.to_i64().filter(|&ps| ps < SMALL_P) {
        return (0..ps).any(|s| {
            let y = eval_mod(h, &Int::from(s), p);
            !y.is_zero() && y.jacobi(p) == 1
        });
    }
    has_nonzero_residue_value_weil(h, p)
}

/// [`has_nonzero_residue_value`] for `p ≥ 17` without a scan: if `h = c·s²` the
/// nonzero values have the class of `c` and `s` has a non-root
/// (`deg s ≤ 2 < p`); otherwise Weil's bound `|Σ χ(h(s))| ≤ 3√p` leaves at least
/// `(p − 4 − 3√p)/2 > 0` residues with `χ(h(s)) = 1`.
fn has_nonzero_residue_value_weil(h: &[Int], p: &Int) -> bool {
    let c = h.last().expect("h ≢ 0").clone();
    let cinv = c.modinv(p).expect("p prime");
    let monic: Vec<Int> = h.iter().map(|x| x.mul(&cinv).rem_euclid(p)).collect();
    if is_square_monic_mod_p(&monic, p) {
        c.jacobi(p) == 1
    } else {
        true
    }
}

/// Whether a monic polynomial of degree ≤ 4 over `𝔽_p` (odd `p`) is a square.
fn is_square_monic_mod_p(f: &[Int], p: &Int) -> bool {
    let inv2 = Int::from(2).modinv(p).expect("p odd");
    let md = |x: Int| x.rem_euclid(p);
    match f.len() - 1 {
        0 => true,
        2 => {
            let a = md(f[1].mul(&inv2));
            md(a.square()) == md(f[0].clone())
        }
        4 => {
            // (s² + A s + B)² = s⁴ + 2A s³ + (A² + 2B) s² + 2AB s + B².
            let a = md(f[3].mul(&inv2));
            let b = md(f[2].sub(&a.square()).mul(&inv2));
            md(a.mul(&b).mul_2k(1)) == md(f[1].clone()) && md(b.square()) == md(f[0].clone())
        }
        _ => false,
    }
}

// ---------------------------------------------------------------------------
// Polynomials over 𝔽_p (coefficients low-to-high, reduced, trimmed).
// ---------------------------------------------------------------------------

fn trim(mut f: Vec<Int>) -> Vec<Int> {
    while f.last().is_some_and(|c| c.is_zero()) {
        f.pop();
    }
    f
}

fn eval_mod(f: &[Int], x: &Int, p: &Int) -> Int {
    let mut acc = Int::ZERO;
    for c in f.iter().rev() {
        acc = acc.mul(x).add(c).rem_euclid(p);
    }
    acc
}

/// `a mod m` for monic `m`.
fn prem(a: &[Int], m: &[Int], p: &Int) -> Vec<Int> {
    let mut r: Vec<Int> = a.iter().map(|c| c.rem_euclid(p)).collect();
    r = trim(r);
    let dm = m.len() - 1;
    while r.len() > dm {
        let k = r.len() - 1 - dm;
        let lead = r.last().unwrap().clone();
        for (i, mc) in m.iter().enumerate() {
            r[k + i] = r[k + i].sub(&lead.mul(mc)).rem_euclid(p);
        }
        r = trim(r);
    }
    r
}

/// `(a / m, a mod m)` for monic `m`.
fn pdivrem(a: &[Int], m: &[Int], p: &Int) -> (Vec<Int>, Vec<Int>) {
    let mut r: Vec<Int> = trim(a.iter().map(|c| c.rem_euclid(p)).collect());
    let dm = m.len() - 1;
    if r.len() <= dm {
        return (Vec::new(), r);
    }
    let mut q = alloc::vec![Int::ZERO; r.len() - dm];
    while r.len() > dm {
        let k = r.len() - 1 - dm;
        let lead = r.last().unwrap().clone();
        q[k] = lead.clone();
        for (i, mc) in m.iter().enumerate() {
            r[k + i] = r[k + i].sub(&lead.mul(mc)).rem_euclid(p);
        }
        r = trim(r);
    }
    (trim(q), r)
}

fn pmulmod(a: &[Int], b: &[Int], m: &[Int], p: &Int) -> Vec<Int> {
    if a.is_empty() || b.is_empty() {
        return Vec::new();
    }
    let mut out = alloc::vec![Int::ZERO; a.len() + b.len() - 1];
    for (i, x) in a.iter().enumerate() {
        for (j, y) in b.iter().enumerate() {
            out[i + j] = out[i + j].add(&x.mul(y));
        }
    }
    prem(&out, m, p)
}

fn ppowmod(base: &[Int], e: &Int, m: &[Int], p: &Int) -> Vec<Int> {
    let mut result = prem(&[Int::ONE], m, p);
    let base = prem(base, m, p);
    for i in (0..e.bit_len()).rev() {
        result = pmulmod(&result, &result, m, p);
        if e.bit(i) {
            result = pmulmod(&result, &base, m, p);
        }
    }
    result
}

fn pmonic(f: Vec<Int>, p: &Int) -> Vec<Int> {
    let f = trim(f);
    match f.last() {
        None => f,
        Some(c) => {
            let inv = c.modinv(p).expect("p prime");
            f.iter().map(|x| x.mul(&inv).rem_euclid(p)).collect()
        }
    }
}

fn pgcd(a: &[Int], b: &[Int], p: &Int) -> Vec<Int> {
    let mut x = pmonic(a.to_vec(), p);
    let mut y = pmonic(b.to_vec(), p);
    while !y.is_empty() {
        let r = pmonic(prem(&x, &y, p), p);
        x = y;
        y = r;
    }
    x
}

/// Distinct roots in `𝔽_p` of `f` (low-to-high, `f ≢ 0`), `p` an odd prime.
fn roots_mod_p(f: &[Int], p: &Int) -> Vec<Int> {
    if f.len() <= 1 {
        return Vec::new();
    }
    if let Some(ps) = p.to_i64().filter(|&ps| ps < SMALL_P) {
        return (0..ps)
            .map(Int::from)
            .filter(|s| eval_mod(f, s, p).is_zero())
            .collect();
    }
    roots_mod_p_cz(f, p)
}

/// [`roots_mod_p`] by Cantor–Zassenhaus (no scan).
fn roots_mod_p_cz(f: &[Int], p: &Int) -> Vec<Int> {
    let f = pmonic(f.to_vec(), p);
    // g = gcd(f, x^p − x): the product of the distinct linear factors.
    let xp = ppowmod(&[Int::ZERO, Int::ONE], p, &f, p);
    let mut xp_minus_x = xp;
    while xp_minus_x.len() < 2 {
        xp_minus_x.push(Int::ZERO);
    }
    xp_minus_x[1] = xp_minus_x[1].sub(&Int::ONE).rem_euclid(p);
    let g = pgcd(&f, &trim(xp_minus_x), p);
    let mut out = Vec::new();
    split_linear(&g, p, &mut out);
    out
}

/// Cantor–Zassenhaus equal-degree splitting of a product of distinct linear
/// factors over `𝔽_p`.
fn split_linear(g: &[Int], p: &Int, out: &mut Vec<Int>) {
    match g.len() {
        0 | 1 => {}
        2 => out.push(g[0].neg().rem_euclid(p)),
        _ => {
            let half = p.sub(&Int::ONE).div_2k_trunc(1);
            let mut delta = Int::ZERO;
            loop {
                let mut h = ppowmod(&[delta.clone(), Int::ONE], &half, g, p);
                if h.is_empty() {
                    h.push(Int::ZERO);
                }
                h[0] = h[0].sub(&Int::ONE).rem_euclid(p);
                let d = pgcd(g, &trim(h), p);
                if d.len() > 1 && d.len() < g.len() {
                    let (q, _) = pdivrem(g, &d, p);
                    split_linear(&d, p, out);
                    split_linear(&pmonic(q, p), p, out);
                    return;
                }
                delta = delta.add(&Int::ONE);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Rational roots of the 2-torsion cubic.
// ---------------------------------------------------------------------------

fn cubic_eval(x: &Int, p: &Int, q: &Int) -> Int {
    x.square().add(p).mul(x).add(q)
}

/// Integer roots of `X³ + p·X + q`, ascending, by exact bisection on the
/// monotone pieces.
fn integer_roots_depressed_cubic(p: &Int, q: &Int) -> Vec<Int> {
    let bound = p.abs().add(&q.abs()).add(&Int::ONE);
    let mut pieces: Vec<(Int, Int, bool)> = Vec::new();
    if !p.is_negative() {
        pieces.push((bound.neg(), bound, true));
    } else {
        // Critical points ±√(−p/3); t = ⌊√(−p/3)⌋.
        let t = Int::from(p.neg().div_floor(&Int::from(3)).magnitude().isqrt());
        pieces.push((bound.neg(), t.neg().sub(&Int::ONE), true));
        pieces.push((t.neg(), t.clone(), false));
        pieces.push((t.add(&Int::ONE), bound, true));
    }
    let mut roots = Vec::new();
    for (mut lo, mut hi, increasing) in pieces {
        if lo > hi {
            continue;
        }
        // Find x in [lo, hi] with f(x) = 0 on a monotone piece.
        while lo <= hi {
            let mid = lo.add(&hi).div_floor(&Int::from(2));
            let fm = cubic_eval(&mid, p, q);
            if fm.is_zero() {
                roots.push(mid);
                break;
            }
            if fm.is_negative() == increasing {
                lo = mid.add(&Int::ONE);
            } else {
                hi = mid.sub(&Int::ONE);
            }
        }
    }
    roots.sort();
    roots.dedup();
    roots
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec;

    #[test]
    fn cubic_roots() {
        // (X − 1)(X − 2)(X + 3) = X³ − 7X + 6.
        assert_eq!(
            integer_roots_depressed_cubic(&Int::from(-7), &Int::from(6)),
            vec![Int::from(-3), Int::from(1), Int::from(2)]
        );
        assert_eq!(
            integer_roots_depressed_cubic(&Int::from(-25), &Int::ZERO),
            vec![Int::from(-5), Int::ZERO, Int::from(5)]
        );
        assert!(integer_roots_depressed_cubic(&Int::from(1), &Int::from(1)).is_empty());
        // X³ + 2X − 12 = (X − 2)(X² + 2X + 6).
        assert_eq!(
            integer_roots_depressed_cubic(&Int::from(2), &Int::from(-12)),
            vec![Int::from(2)]
        );
    }

    #[test]
    fn large_prime_roots_and_squares() {
        let p = Int::from(1_000_003);
        // (x − 5)(x − 7)(x² + 1) has roots 5, 7 (and ±i iff p ≡ 1 mod 4).
        let f = [
            Int::from(35),
            Int::from(-12),
            Int::from(36),
            Int::from(-12),
            Int::from(1),
        ];
        let mut r = roots_mod_p(&f, &p);
        r.sort();
        let mut expect = vec![Int::from(5), Int::from(7)];
        if p.rem_euclid(&Int::from(4)).is_one() {
            let i = Int::from(-1).sqrt_mod(&p).unwrap();
            expect.push(i.clone());
            expect.push(p.sub(&i));
        }
        expect.sort();
        assert_eq!(r, expect);
        // (s² + 3s + 4)² is a square.
        let sq = [
            Int::from(16),
            Int::from(24),
            Int::from(17),
            Int::from(6),
            Int::from(1),
        ];
        assert!(is_square_monic_mod_p(&sq, &p));
        assert!(!is_square_monic_mod_p(&f, &p));
    }

    #[test]
    fn large_prime_paths_match_scan() {
        // The scan-free paths agree with exhaustive scans for 17 ≤ p < 400.
        let mut seed = 0x2545_f491_4f6c_dd1du64;
        let mut next = |m: i64| {
            seed ^= seed << 13;
            seed ^= seed >> 7;
            seed ^= seed << 17;
            (seed % m as u64) as i64
        };
        let mut p = Int::from(17);
        while p < Int::from(400) {
            let ps = p.to_i64().unwrap();
            for trial in 0..60 {
                let deg = 1 + trial % 4;
                let mut f: Vec<Int> = (0..=deg).map(|_| Int::from(next(ps))).collect();
                if trial % 3 == 0 {
                    // Force a constant times a square: c·(s² + A s + B)².
                    let (c, a, b) = (1 + next(ps - 1), next(ps), next(ps));
                    let q = [b * b, 2 * a * b, a * a + 2 * b, 2 * a, 1];
                    f = q.iter().map(|x| Int::from(x * c).rem_euclid(&p)).collect();
                }
                let f = trim(f);
                if f.is_empty() {
                    continue;
                }
                let scan = (0..ps).any(|s| {
                    let y = eval_mod(&f, &Int::from(s), &p);
                    !y.is_zero() && y.jacobi(&p) == 1
                });
                assert_eq!(
                    scan,
                    has_nonzero_residue_value_weil(&f, &p),
                    "p={p} f={f:?}"
                );
                let mut cz = roots_mod_p_cz(&f, &p);
                cz.sort();
                let brute: Vec<Int> = (0..ps)
                    .map(Int::from)
                    .filter(|s| eval_mod(&f, s, &p).is_zero())
                    .collect();
                assert_eq!(cz, brute, "p={p} f={f:?}");
            }
            p = p.next_prime();
        }
    }

    #[test]
    fn global_search_consistent_with_selmer() {
        // Every class with a found global point must be in the Selmer group.
        for (a, b) in [
            (0i64, -25i64),
            (0, -36),
            (0, 17),
            (0, -68),
            (3, 2),
            (-1, -6),
        ] {
            let (a, b) = (Int::from(a), Int::from(b));
            let data = selmer_data(&a, &b, 30);
            let primes = distinct_primes(&b);
            for mask in 0..(1u64 << (primes.len() + 1)) {
                let d = mask_to_int(mask, &primes);
                let e = b.div_exact(&d);
                if quartic_has_global_point(&d, &a, &e, 30) {
                    assert!(data.selmer.contains(&d), "a={a} b={b} d={d}");
                }
            }
        }
    }
}
